Include all pages in search index
gethyas/doks-core pull request #35
Opened 2023-08-01 16:17 UTC by salim-b

## Summary

Include all pages in search index.

## Motivation

Sections, taxonomies and terms were not included in the search index before, although they often contain relevant site content.

## Caveats

Maybe you want to make this configurable by the user, so they can choose whether to include `site.Pages` or only `site.RegularPages` in the search index via an additional config option like `site.Data.doks.indexAllPages` (`true`/`false`). Let me know if I should extend this PR to do so.

## Checks

- [x] Read [Create a Pull Request](https://gethyas.com/docs/contributing/how-to-contribute/#create-a-pull-request)
- [x] Supports all screen sizes (if relevant)
- [x] Supports both light and dark mode (if relevant)
- [ ] Passes `npm run test`

2023-08-03 12:57 UTC, h-enk requested changes
It would be great if you could make this an option — like you proposed.

2023-08-04 04:17 UTC, salim-b commented
I've updated the PR with an even better config approach, see updated summary above.

2023-08-10 20:20 UTC, salim-b commented
Sorry, I made a mess with the different PR  branches. I now properly rebased, should be good to merge.

2023-08-11 08:27 UTC, h-enk approved these changes
Wow, brilliant — this is a super powerful setup! Fully tested and verified.

2023-08-11 08:27 UTC, merged